- main/src/main/java/tw/firemaples/onscreenocr/floatings/result/FontSizeAdjuster.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/result/ResultView.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/result/ResultViewModel.kt
- main/src/main/java/tw/firemaples/onscreenocr/pref/AppPref.kt
- main/src/main/java/tw/firemaples/onscreenocr/utils/Constants.kt
- main/src/main/java/tw/firemaples/onscreenocr/utils/Utils.kt
- main/src/main/res/drawable/ic_font_size.xml
- main/src/main/res/layout/view_font_size_adjuster.xml
- main/src/main/res/layout/view_result_panel.xml
- main/src/main/res/values-zh-rCN/strings.xml
- main/src/main/res/values-zh-rTW/strings.xml
- main/src/main/res/values/strings.xml
I tried to create buttons to increase decrease font size
it works but could you 
1- create a button to show and hide increase decrease buttons 
so no one click them by mistake 
2-  change the icons :)
> button increase decrease font size

- main/src/main/java/tw/firemaples/onscreenocr/pages/launch/permissions/PermissionCaptureScreenFragment.kt
- main/src/main/java/tw/firemaples/onscreenocr/pages/launch/permissions/PermissionFloatWindowFragment.kt
- main/src/main/java/tw/firemaples/onscreenocr/utils/Utils.kt
- main/src/main/res/layout/permission_capture_screen_fragment.xml
- main/src/main/res/layout/permission_float_window_fragment.xml
- main/src/main/res/values-zh-rCN/strings.xml
- main/src/main/res/values-zh-rTW/strings.xml
- main/src/main/res/values/strings.xml
on google play some Arabic reviews said the app close by it self after some time I think the reason is battery optimization
what I hope you could improve 
- the button should exist if the battery optimization is on using 
- PowerManager.isIgnoringBatteryOptimizations()
- add strings
> battery optimization

- main/src/main/java/tw/firemaples/onscreenocr/pages/launch/permissions/PermissionCaptureScreenFragment.kt
- main/src/main/java/tw/firemaples/onscreenocr/pages/setting/SettingFragment.kt
- main/src/main/res/layout/permission_capture_screen_fragment.xml
- main/src/main/res/layout/permission_float_window_fragment.xml
- main/src/main/res/values-zh-rCN/strings.xml
- main/src/main/res/values-zh-rTW/strings.xml
- main/src/main/res/values/strings.xml
- main/src/main/res/xml/perference.xml
hide requestBattery at the beginning  so it won't show two buttons
> Move requestBattery to settings page

- main/src/main/res/layout/floating_main_bar.xml
- main/src/main/res/layout/floating_menu.xml
- main/src/main/res/layout/floating_result_view.xml
- main/src/main/res/layout/floating_text_info_search.xml
layouts does not support RTL (languages)
that's why I decided to force LTR on them
> Force some layout display in LTR

- main/src/main/AndroidManifest.xml
- main/src/main/java/tw/firemaples/onscreenocr/floatings/main/MainBar.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/main/MainBarViewModel.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/result/ResultView.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/result/ResultViewModel.kt
- main/src/main/java/tw/firemaples/onscreenocr/log/FirebaseEvent.kt
- main/src/main/java/tw/firemaples/onscreenocr/repo/TranslationRepository.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/BaseAppTranslator.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/BingTranslateAppTranslator.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/GoogleTranslateAppTranslator.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/OtherTranslateAppTranslator.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/PapagoTranslateAppTranslator.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/Translator.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/YandexTranslateAppTranslator.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/utils/BingTranslateUtils.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/utils/GoogleTranslateUtils.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/utils/OtherTranslateUtils.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/utils/PapagoTranslateUtils.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/utils/TranslatorUtils.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/utils/YandexTranslateUtils.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/yandexTranslateAppTranslator.kt
- main/src/main/java/tw/firemaples/onscreenocr/utils/Constants.kt
- main/src/main/res/drawable/ic_microsoft_bing.xml
- main/src/main/res/drawable/ic_open_in_app.xml
- main/src/main/res/layout/floating_main_bar.xml
- main/src/main/res/values-zh-rCN/strings.xml
- main/src/main/res/values-zh-rTW/strings.xml
- main/src/main/res/values/strings.xml
add 3 new apps
bing translator app
Papago translator app
yandex translator app
> Support Papago, Bing, Yandex and other 3rd-party translation apps

- main/src/main/res/drawable/ic_splash.xml
- main/src/main/res/layout/activity_launch.xml
- main/src/main/res/layout/activity_setting.xml
- main/src/main/res/layout/floating_dialog.xml
- main/src/main/res/layout/floating_main_bar.xml
- main/src/main/res/layout/floating_result_view.xml
- main/src/main/res/layout/floating_text_info_search.xml
- main/src/main/res/layout/floating_translation_select_panel.xml
- main/src/main/res/layout/item_lang_list.xml
- main/src/main/res/layout/item_menu.xml
- main/src/main/res/layout/item_menu_checkable.xml
- main/src/main/res/layout/view_help.xml
- main/src/main/res/layout/view_recognized_text_editor.xml
- main/src/main/res/layout/view_result_panel.xml
- main/src/main/res/values-ar/strings.xml
> try to fix some xml warnings

- main/src/main/java/tw/firemaples/onscreenocr/CoreApplication.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/ViewHolderService.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/base/FloatingView.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/base/FloatingViewModel.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/base/MovableFloatingView.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/manager/FloatingStateManager.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/menu/MenuView.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/screenCircling/CircleGestureAdapter.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/screenCircling/HelperTextView.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/translationSelectPanel/TranslationSelectPanel.kt
- main/src/main/java/tw/firemaples/onscreenocr/log/UserInfoUtils.kt
- main/src/main/java/tw/firemaples/onscreenocr/pages/BaseFragment.kt
- main/src/main/java/tw/firemaples/onscreenocr/pref/AppPref.kt
- main/src/main/java/tw/firemaples/onscreenocr/remoteconfig/RemoteConfigManager.kt
- main/src/main/java/tw/firemaples/onscreenocr/remoteconfig/data/TrainedDataFileNames.kt
- main/src/main/java/tw/firemaples/onscreenocr/repo/GeneralRepository.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/GoogleMLKitTranslator.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/Translator.kt
- main/src/main/java/tw/firemaples/onscreenocr/utils/UIUtils.kt
try to fix some kotlin warnings
> try to fix some kotlin warnings

- main/src/main/java/tw/firemaples/onscreenocr/pages/setting/SettingManager.kt
> Increase default opaque percentage

- main/src/main/java/tw/firemaples/onscreenocr/floatings/translationSelectPanel/TranslationSelectPanel.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/translationSelectPanel/TranslationSelectPanelViewModel.kt
- main/src/main/java/tw/firemaples/onscreenocr/pref/AppPref.kt
- main/src/main/res/drawable/ic_heart.xml
> Let can saving favorite languages

- main/src/main/java/tw/firemaples/onscreenocr/floatings/result/ResultView.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/result/ResultViewModel.kt
- main/src/main/java/tw/firemaples/onscreenocr/pref/AppPref.kt
- main/src/main/java/tw/firemaples/onscreenocr/utils/UIUtils.kt
- main/src/main/res/color/icon_result_panel_checkable.xml
- main/src/main/res/drawable/ic_text_search.xml
- main/src/main/res/layout/view_result_panel.xml
> Add an option to enable/disable text selectable on the result window

- .github/workflows/ci.yml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- main/build.gradle
> Revert Gradle version upgrade to fix Microsoft Azure translation error

- .github/workflows/ci.yml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- main/build.gradle
- main/src/androidTest/java/tw/firemaples/onscreenocr/repo/OCRRepositoryTest.kt
- main/src/main/java/tw/firemaples/onscreenocr/floatings/base/FloatingView.kt
- main/src/main/java/tw/firemaples/onscreenocr/repo/OCRRepository.kt
still theres warning in  Task :main:compileDevDebugKotlin
> update libraries + fix some build bugs

- main/src/main/java/tw/firemaples/onscreenocr/floatings/manager/FloatingStateManager.kt
- main/src/main/java/tw/firemaples/onscreenocr/translator/GoogleMLKitTranslator.kt
> Check transation environment before capturing screen

- main/src/main/java/tw/firemaples/onscreenocr/screenshot/ScreenExtractor.kt
- main/src/main/java/tw/firemaples/onscreenocr/utils/Constants.kt
Reverts firemaples/EverTranslator#291
> Revert "Skip whole-black screenshots"

- main/src/main/java/tw/firemaples/onscreenocr/log/FirebaseEvent.kt
- main/src/main/java/tw/firemaples/onscreenocr/screenshot/ScreenExtractor.kt
> Ignore known error in Crashlytics

- main/src/main/java/tw/firemaples/onscreenocr/recognition/GoogleMLKitTextRecognizer.kt
- main/src/main/java/tw/firemaples/onscreenocr/utils/Utils.kt
Support reading text from right-to-left in Japanese and Chinese
| RTL selection | RTL result |
|--------|--------|
| <img width='300px' src='https://github.com/firemaples/EverTranslator/assets/5812567/7ab9d190-1194-4c0d-96a5-88cb6a15a486' /> | <img width='300px' src='https://github.com/firemaples/EverTranslator/assets/5812567/911ee311-29e7-4f48-b214-5f1d1324c228' /> | 
Close #336
> Support reading text from right-to-left in Japanese and Chinese

- main/src/main/java/tw/firemaples/onscreenocr/utils/WordBoundary.kt
| Before | After |
|--------|--------|
| <img width='300' src='https://github.com/firemaples/EverTranslator/assets/5812567/2e8e993d-6a93-40f0-9001-d82763586714' /> | <img width='300' src='https://github.com/firemaples/EverTranslator/assets/5812567/5b3c57ed-194d-44be-aa8c-dc385aa00ca4' /> |
> Skip word boundary with blank + dash pattern

- main/src/main/java/tw/firemaples/onscreenocr/floatings/compose/mainbar/MainBarContent.kt
| Before | After |
|--------|--------|
| <img width="221" alt="image" src="https://github.com/firemaples/EverTranslator/assets/5812567/58c4a453-816c-4ce7-8df9-325a5030256b"> | <img width="226" alt="image" src="https://github.com/firemaples/EverTranslator/assets/5812567/c18f4e33-4ecb-4dbf-b87f-434ac727d388"> |
> Update MainBar button tint color

- main/src/main/java/tw/firemaples/onscreenocr/floatings/compose/resultview/ResultViewContent.kt
> Temporarily remove the animations on the result view

- main/src/main/java/tw/firemaples/onscreenocr/floatings/compose/mainbar/MainBarViewModel.kt
Reshedule the fade-out task after the menu bar is closed
| Before | After |
|--------|--------|
| <video width='300' src='https://github.com/firemaples/EverTranslator/assets/5812567/117f06bd-1d91-4906-b228-3b540d70919d' /> | <video width='300' src='https://github.com/firemaples/EverTranslator/assets/5812567/74d2b12e-e1b3-4cdc-972a-94d7797167fb' /> |
> Reschedule main bar fade out after closing the menu

- .github/pull_request_template.md
Create a pull-request template
> Create pull-request template
